Numpy - 1. Provides us n-dim Array

Used to perform mathametical and statistical operations on numerical data.


In [2]:
import numpy as np

In [3]:
# 1d array
arr_1_d = np.array([12, 54, 87, 98])

# 2d array
arr_2_d = np.array([[12, 54, 87], [56, 78, 32]])

# 3d array
arr_3_d = np.array([[[12, 23, 34], [21, 32, 43]], [[56, 67, 78], [54, 65, 76]]])

In [4]:
arr_3_d

array([[[12, 23, 34],
        [21, 32, 43]],

       [[56, 67, 78],
        [54, 65, 76]]])

In [5]:
# ndim -> is used to check the dimentions of an array.
arr_3_d.ndim


3

In [6]:
# ndarray
arr_n_d = np.array([12, 54, 87, 98], ndmin=15)  # for 15d array
arr_n_d

array([[[[[[[[[[[[[[[12, 54, 87, 98]]]]]]]]]]]]]]])

In [7]:
arr_1_d[2]

np.int64(87)

In [8]:
arr_2_d = np.array([[12, 54, 87], [56, 78, 32]])

In [9]:
arr_2_d[1, 0]

np.int64(56)

In [10]:
arr_3_d = np.array([[[12, 23, 34], [21, 32, 43]], [[56, 67, 78], [54, 65, 76]]])

In [11]:
arr_3_d[1, 1, 1]

np.int64(65)

In [12]:
arr_3_d[0, 1, 2]

np.int64(43)

In [13]:
arr_3_d[1, 0, 2]

np.int64(78)

In [14]:
arr_3_d.shape
# output:(2, 2, 3)  rows=2, col=2, inside the element=3

(2, 2, 3)

In [15]:
arr_3_d1 = np.array(
    [
        [[12, 23, 34, 45, 44], [21, 32, 43, 8, 9]],
        [[56, 67, 78, 7, 8], [54, 65, 76, 7, 9]],
    ]
)
arr_3_d1
arr_3_d1.shape
# output:(2, 2, 5)  rows=2, col=2, inside the element=5

(2, 2, 5)

In [16]:
arr_3_d2 = np.array(
    [
        [[12, 23, 34, 45, 44], [21, 32, 43, 8, 9], [4, 5, 6, 7, 7]],
        [[56, 67, 78, 7, 8], [54, 65, 76, 7, 9], [1, 2, 3, 4, 5]],
    ]
)

arr_3_d2.shape
# output:(2, 3, 5)  rows=2, col=3, inside the element=5

(2, 3, 5)

In [17]:
## arr[start:end:step] // sclicing
arr_1_d[
    0:3
]  # start from 0 to 3, but not including 3 because of end index it is exclusive

array([12, 54, 87])

In [18]:
arr_1_d = np.array([12, 54, 87, 98])
arr_1_d[0:3]


array([12, 54, 87])

In [19]:
arr_2_d = np.array([[12, 54, 87], [56, 78, 32]])
arr_2_d[0:2, 0:2]  # [Rows,columns]


array([[12, 54],
       [56, 78]])

In [20]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b[0:2, 1:3])  # Rows 0-1, Columns 1-2
# Output:
# [[2 3]
#  [5 6]]

[[2 3]
 [5 6]]


In [21]:
arr_2_d[-2, :-2]

array([12])

In [22]:
arr_3_d2 = np.array(
    [
        [[12, 23, 34, 45, 44], [21, 32, 43, 8, 9], [4, 5, 6, 7, 7]],
        [[56, 67, 78, 7, 8], [54, 65, 76, 7, 9], [1, 2, 3, 4, 5]],
    ]
)

In [23]:
arr_3_d2 = np.array(
    [
        [  # Block 0
            [12, 23, 34, 45, 44],  # Row 0
            [21, 32, 43, 8, 9],  # Row 1
            [4, 5, 6, 7, 7],  # Row 2
        ],
        [  # Block 1
            [56, 67, 78, 7, 8],  # Row 0
            [54, 65, 76, 7, 9],  # Row 1
            [1, 2, 3, 4, 5],  # Row 2
        ],
    ]
)

In [24]:
arr_3_d2[0, 1]


# Output: [21, 32, 43, 8, 9]

array([21, 32, 43,  8,  9])

In [25]:
arr_3_d2[1, 2, 3]  # [block][row][column]

# Output: 4


np.int64(4)

In [26]:
arr_3_d2[:, :, 2]  # [block][row][column]
# Output:
# [[34 43  6]
#  [78 76  3]]


array([[34, 43,  6],
       [78, 76,  3]])

In [27]:
arr_3_d2[
    1, :, :2
]  # Selects block at index 1 (second 2D block), all rows (:), and first two columns (indices 0 and 1 only; :2 is exclusive of index 2)
# Output:
# [[56 67]
#  [54 65]
#  [ 1  2]]
# ------------------------------------------------------------------------
# #In Python slicing, "exclusive" means:
# The stop index is not included in the result.

# So when you write :2, you're telling Python:

# "Start from index 0 and go up to, but not including index 2."
# ----------------
# #Example: a = [10, 20, 30, 40, 50]
# print(a[:2])  # Output: [10, 20]
# Explanation:

# a[:2] includes:

# index 0 → 10

# index 1 → 20

# It excludes=বাদ index 2 (which is 30).


array([[56, 67],
       [54, 65],
       [ 1,  2]])

In [28]:
arr = np.array([12, 45, 78, 98, 65, 32, 45, 65])
arr.shape

(8,)

In [29]:
a, b = arr.reshape((2, 4))  # 2 rows, 4 columns

In [30]:
a

array([12, 45, 78, 98])

In [31]:
b

array([65, 32, 45, 65])

In [32]:
arr = np.array([12, 54, 98, 78, 40])

In [33]:
new_arr = arr.reshape((5, 1))

In [34]:
new_arr

array([[12],
       [54],
       [98],
       [78],
       [40]])

In [35]:
new_arr.shape

(5, 1)

In [36]:
new_arr.ndim

2

In [37]:
new_arr.dtype

dtype('int64')

In [38]:
# it is used to check the data type of an array
# default data type is int64
# i changed it to int16
a = np.array([1, 2, 3], dtype="int16")
print(a)

[1 2 3]


In [39]:
new_arr.dtype

dtype('int64')

In [40]:
a = np.array([1, 2, 3], dtype="int16")
print(a)

[1 2 3]


In [41]:
a.dtype

dtype('int16')

In [42]:
a.itemsize  # itemsize returns the size in bytes of each element in the array

2

In [43]:
a.nbytes  # nbytes returns the total number of bytes consumed by the elements of the array

6

In [44]:
a = np.array(
    [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [45]:
a[0, :]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a[:, 2]

array([ 3, 13])

In [47]:
a[0, 1:-1:2]

array([2, 4, 6, 8])

In [48]:
a[1, 5] = 20

a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7  8  9 10]
 [11 12  2 14 15 20 17 18 19 20]]


In [49]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [50]:
arr = np.array([21, 54, 98, 87, 65])  # 1D Array

In [51]:
len(arr)

5

In [52]:
# use for loop
for i in arr:
    print(i)

21
54
98
87
65


In [53]:
# use while loop
i = 0
while i < len(arr):
    print(arr[i])
    i += 1


21
54
98
87
65


In [54]:
arr2 = np.array([[54, 87, 98, 54], [12, 56, 89, 78]])  # 2d array

In [55]:
for i in arr2:
    for j in i:
        print(j)

54
87
98
54
12
56
89
78


In [56]:
arr3 = np.array(
    [[[32, 54, 98, 87], [12, 45, 87, 98]], [[12, 45, 78, 98], [74, 85, 96, 14]]]
)  # 3d Array

In [57]:
 #check occurance / Frequency Counting

freq = {} # Dictionary to store frequency of each element
 #check occurance / Frequency Counting
for i in arr3: # 2 times
  for j in i: # 4 times
    for k in j: # 16 times
      if k in freq:
        freq[k] += 1
      else:
        freq[k] = 1


In [58]:
freq

{np.int64(32): 1,
 np.int64(54): 1,
 np.int64(98): 3,
 np.int64(87): 2,
 np.int64(12): 2,
 np.int64(45): 2,
 np.int64(78): 1,
 np.int64(74): 1,
 np.int64(85): 1,
 np.int64(96): 1,
 np.int64(14): 1}

In [59]:
arr1 = np.array([[21,54,98],[54,98,87]])
arr2 = np.array([[54,98,65],[21,54,98]])

In [60]:
#concatenate
new_arr = np.concatenate((arr1, arr2))

In [61]:
a,b,c,d = np.split(new_arr, 4)

In [62]:
a

array([[21, 54, 98]])

In [63]:
b

array([[54, 98, 87]])

In [64]:
c

array([[54, 98, 65]])

In [65]:
d

array([[21, 54, 98]])

In [66]:
np.mean(arr)

np.float64(65.0)

In [67]:
#median means the middle value of a sorted array.
np.median(arr)


np.float64(65.0)

In [ ]:
np.std(arr) # Standard deviation measures the amount of variation or dispersion in a set of values.

np.float64(26.94438717061496)

In [ ]:
np.max(arr) 

np.int64(98)

In [ ]:
np.min(arr)  

np.int64(21)